name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  server-build:
    name: server-build
    uses: ./.github/workflows/server-build.yml
    secrets: inherit
    with:
      pr: 0
      skip-tests: "true"

  client-build:
    name: client-build
    uses: ./.github/workflows/client-build.yml
    secrets: inherit
    with:
      pr: 0

  rts-build:
    name: rts-build
    uses: ./.github/workflows/rts-build.yml
    secrets: inherit
    with:
      pr: 0

  build-and-push-image:
    needs: [client-build, server-build, rts-build]
    if: success()
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download the client build artifact
        uses: actions/download-artifact@v4
        with:
          name: client-build
          path: app/client

      - name: Unpack the client build artifact
        run: |
          mkdir -p app/client/build
          tar -xvf app/client/build.tar -C app/client/build

      - name: Download the server build artifact
        uses: actions/download-artifact@v4
        with:
          name: server-build
          path: app/server/dist/

      - name: Download the rts build artifact
        uses: actions/download-artifact@v4
        with:
          name: rts-dist
          path: app/client/packages/rts/dist

      - name: Untar the rts folder
        run: |
          tar -xvf app/client/packages/rts/dist/rts-dist.tar -C app/client/packages/rts/
          rm app/client/packages/rts/dist/rts-dist.tar

      - name: Generate info.json
        run: scripts/generate_info_json.sh

      - name: Place server artifacts
        run: scripts/prepare_server_artifacts.sh

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          image="ghcr.io/${{ github.repository }}:${GITHUB_REF_NAME//\//-}"
          image_latest="ghcr.io/${{ github.repository }}:latest"

          docker build \
            --build-arg BASE=appsmith/base-ce:release \
            --build-arg APPSMITH_CLOUD_SERVICES_BASE_URL=https://release-cs.appsmith.com \
            -t "$image" \
            -t "$image_latest" \
            .

          docker push "$image"
          docker push "$image_latest"
